name: ml-workshop
channels:
  - pytorch
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.9.4=pyhd8ed1ab_0
  - astor=0.8.1=pyhd8ed1ab_1
  - autograd=1.6.2=pyhd8ed1ab_0
  - autograd-gamma=0.5.0=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcftools=1.12=h45bccc9_1
  - blas=1.0=mkl
  - blessings=1.7=py39hf3d152e_1006
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py39h3d6467e_1
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bwa-mem2=2.2.1=hd03093a_5
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.14.12=h8948797_3
  - captum=0.7.0=pyhd8ed1ab_0
  - catboost=1.2.7=py39hf3d152e_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.15.0=py39hd667e15_1
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorlog=6.9.0=pyh707e725_1
  - conda=23.5.0=py39hf3d152e_1
  - conda-package-handling=1.8.1=py39h7f8727e_0
  - cryptography=39.0.0=py39hd598818_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dataclasses=0.8=pyhc8e2a94_3
  - decorator=5.1.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fmt=9.1.0=h924138e_0
  - fontconfig=2.13.96=ha180cfb_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h7b6447c_0
  - future=1.0.0=pyhd8ed1ab_2
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.56.2=hd408876_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gpustat=0.6.0=pyhd8ed1ab_1
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.38.0=hcf1ce16_1009
  - greenlet=3.0.3=py39h3d6467e_0
  - gsl=2.6=he838d99_2
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - htslib=1.12=h9093b5e_1
  - huggingface_hub=0.30.2=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imbalanced-learn=0.12.3=pyhd8ed1ab_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - ipython=7.29.0=py39hef51801_2
  - ipywidgets=8.0.7=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py39hf3d152e_3
  - jpeg=9d=h7f8727e_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h9c3ff4c_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libarchive=3.5.2=hb890918_3
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=he0ac6c6_5
  - libmamba=0.24.0=hd8a31e3_1
  - libmambapy=0.24.0=py39hd55135b_1
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsentencepiece=0.2.0=he81a138_2
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.24=hfc55251_1
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.3.0=h6f004c6_2
  - libtool=2.4.7=h27087fc_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.3=hcbfbd50_0
  - libzlib=1.2.13=hd590300_5
  - lifelines=0.30.0=pyhd8ed1ab_1
  - llvmlite=0.39.1=py39h7d9a04d_1
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h7b6447c_2
  - mako=1.3.10=pyhd8ed1ab_0
  - mamba=0.24.0=py39hfa8f2c8_1
  - matplotlib-base=3.5.2=py39h700656a_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nltk=3.9.1=pyhd8ed1ab_1
  - numba=0.56.4=py39h61ddf18_0
  - nvidia-ml=7.352.0=py_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openjdk=8.0.152=h7b6447c_3
  - openssl=1.1.1w=hd590300_0
  - optuna=4.4.0=pyhd8ed1ab_0
  - pango=1.40.14=he752989_2
  - parallel=20220922=ha770c72_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre=8.45=h295c915_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39h5aabda8_0
  - pixman=0.40.0=h7f8727e_1
  - plotly=5.19.0=pyhd8ed1ab_0
  - pluggy=1.2.0=pyhd8ed1ab_0
  - psutil=5.8.0=py39h27cfd23_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.15=h47a2c10_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pyvcf=0.6.8=py39hde42818_1002
  - readline=8.2=h8228510_1
  - regex=2024.7.24=py39hcd6043d_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.32.3=pyhd8ed1ab_1
  - ruamel.yaml=0.17.32=py39hd1e30aa_0
  - ruamel.yaml.clib=0.2.7=py39h72bdee0_1
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - sambamba=0.6.6=2
  - samtools=1.1=h50ea8bc_8
  - sentencepiece=0.2.0=hf3d152e_2
  - sentencepiece-python=0.2.0=py39h4f2c52d_2
  - sentencepiece-spm=0.2.0=he81a138_2
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlalchemy=1.4.49=py39hd1e30aa_1
  - sqlite=3.36.0=hc218d9a_0
  - statsmodels=0.13.5=py39h7deecbd_1
  - tenacity=8.2.2=py39h06a4308_0
  - tk=8.6.12=h27826a3_0
  - tmux=3.1=h1c4e50f_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - trimmomatic=0.39=hdfd78af_2
  - tzdata=2021e=hda174b7_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxpm=3.5.16=hd590300_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.7.0=h27087fc_2
  - zeromq=4.3.4=h9c3ff4c_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py39h6e5214e_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - anyio==4.9.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.0.8
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - biopython==1.79
      - bleach==6.2.0
      - cachetools==5.3.1
      - charset-normalizer==2.0.7
      - click==8.1.7
      - colorama==0.4.5
      - comm==0.2.2
      - cycler==0.11.0
      - cython==0.29.35
      - datasets==2.18.0
      - debugpy==1.8.13
      - defusedxml==0.7.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docutils==0.19
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==1.0.0
      - fastjsonschema==2.17.1
      - filelock==3.13.4
      - flatbuffers==1.12
      - fonttools==4.28.1
      - formulaic==0.6.4
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.10.0
      - grpcio==1.47.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - icecream==2.1.3
      - ignite==1.1.0
      - importlib-metadata==4.12.0
      - ipykernel==6.29.5
      - isoduration==20.11.0
      - iterative-stratification==0.1.7
      - jinja2==3.1.6
      - joblib==1.1.1
      - json5==0.12.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - keras==2.9.0
      - kiwisolver==1.3.2
      - lazypredict==0.2.12
      - libclang==14.0.6
      - lightgbm==4.3.0
      - markupsafe==3.0.2
      - matplotlib==3.5.0
      - mistune==3.1.3
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.9.0
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numpy==1.23.5
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pathlib==1.0.1
      - pip==24.3.1
      - platformdirs==4.3.7
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==3.19.4
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyfaidx==0.7.2.1
      - pyparsing==2.4.7
      - pyrsistent==0.19.3
      - pysam==0.21.0
      - python-graphviz==0.21
      - python-json-logger==3.3.0
      - pytorch-ignite==0.4.10
      - pytorch-tabnet==4.1.0
      - pytz==2021.3
      - pyyaml==6.0.1
      - pyzmq==26.4.0
      - referencing==0.36.2
      - reload==0.9
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.0.2
      - scipy==1.7.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==1.40.0
      - setproctitle==1.3.3
      - setuptools-scm==6.3.2
      - shap==0.46.0
      - sklearn==0.0
      - slicer==0.0.8
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - statistics==1.0.3.5
      - tabpfn==0.1.10
      - tabulate==0.9.0
      - terminado==0.18.1
      - threadpoolctl==3.0.0
      - tinycss2==1.4.0
      - tokenizers==0.13.3
      - tomli==1.2.2
      - torchmetrics==0.9.3
      - torchsummary==1.5.1
      - torchviz==0.0.2
      - tornado==6.4.2
      - tqdm==4.62.3
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.1
      - uri-template==1.3.0
      - urllib3==1.26.18
      - wandb==0.16.3
      - watchdog==2.1.9
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wrapt==1.14.1
      - xgboost==2.1.3
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.16.2
